on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * *'
name: Scrape Data
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      working-directory: ./scraper
      run: npm install
    - name: Scrape
      env:
        DB_PATH: ../client/data/db.json
      working-directory: ./scraper
      run: npm run scraper
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you
